### PR TITLE
Replaced Curse API v2 with v3

### PR DESCRIPTION
**Pull request by Somrlik**
- Changed CurseMetaAPI to call v3
 - Changed models to accept parameters from v3
 - Minor improvement to FileChooser in DestinationPaneController
 - Added .editorconfig and some stuff to .gitignore

### CODE REVIEW

**Comment by skyecodes** [comment]
Thanks a lot ! Will look into this tomorrow.

**Comment by skyecodes** [comment]
Haha! I was writing a message to show you this minor mistake. I'm testing and it seems to be working, I'll merge in a few moments.

**Comment by Somrlik** [comment]
@Franckyi Cool, I was glad to help :+1:

Nice code BTW, fixing any other CMPDL would be a hassle (I tried), but this was a blast!

**Comment by skyecodes** [comment]
@Somrlik Thanks ;)
I'm in the process of rewriting it (the codebase is good but quite old for me) to fix some bugs and improve the user experience.

**Pull request merged**
